### ISSUE TITLE
Incorrect volume format

### ISSUE THREAD

**Issue by matejsp** [aramean/go-podman-compose#1]
|**| Error: ${APP_ROOT_DIR:-.}/docker/memcached/memcached:/etc/sysconfig/memcached:cached: incorrect volume format, should be [host-dir:]ctr-dir[:option]

It works with podman-compose & docker compose.

```
---
version: '3.8'

services:
  memcached:
    image: memcached:latest
    platform: linux/amd64
    ports:
      - '58000:11211'
    volumes:
      - ${APP_ROOT_DIR:-.}/docker/memcached/memcached:/etc/sysconfig/memcached:cached
```
