### ISSUE TITLE
Network support

### ISSUE THREAD

**Issue by hannotauber** [aramean/go-podman-compose#4]
Add `networks` support.

```
podman network create test
```
```yaml
version: "3.9"

services:
  wordpress:
    image: quay.io/libpod/alpine_nginx:latest
    ports:
      - "8080:80"
    networks:
      - test
```
```
podman inspect web
podman network inspect web
```

Expected behavior for web container to be in test network.
